---
title: "Teori Portofolio dan Analisis Investasi"
description: |
  Kode Mata Kuliah/SKS: EKSI4203/3 SKS
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  R.options = list(width = 60)
)
```
Tutor: [Tedy Herlambang](https://bangtedy.github.io)

### Deskripsi Singkat

Mata kuliah ini membahas kerangka konsep dasar manajemen investasi, pengertian pasar, instrumen diperdagangkan dan mekenisme perdagangan, teori resiko dan return, pemilihan portofolio, obligasi, saham,sekuritas derivative dan teori investasi modern.

### Kompetensi Umum

Secara umum setelah mempelajari modul ini, diharapkan agar mahasiswa dapat memahami bagaimana mencari dana dan menggunakan dana secara efisien agar tujuan perusahaan dapat tercapai.

Tutorial dilakukan sebanyak 8 kali mencakup 9 modul. Topik-topik yang akan dibahas sebagai berikut:

:::obj

* Minggu 1 Investasi
* Minggu 2 Pasar Modal
* Minggu 3 *Return* dan Risiko
* Minggu 4 Saham
* Minggu 5 Instrumen Pendapatan Tetap
* Minggu 6 Konsep Portofolio
* Minggu 7 Model Keseimbangan dan Beta
* Minggu 8 *Online Trading*, Membuat Sendiri Portofolio dan Investasi di Reksadana

:::

### Referensi Utama:

1. Hartono, Jogiyanto (2015) Teori Portofolio dan Analisis Investasi. Buku Materi Pokok EKSI4203. Edisi 3. Penerbit Universitas Terbuka. Tangerang

### Referensi Tambahan:

1. Brigham, Eugene F. dan Joel F. Houston (2015) Fundamentals of Financial Management,
Concise Eighth Edition. Cengage

2. Elton, Edwin J., Martin J. Gruber, Stephen J. Brown, William N. Goetzmann (2014). Modern portfolio theory and investment analysis, 9th edition. Wiley.