---
title: Konsep Portofolio
author: Tedy Herlambang
date: '2022-05-17'
slug: konsep-portofolio
categories:
  - Materi
tags:
  - attainable set
  - efficient set
  - Markowitz
---

```{r load_packages, echo=FALSE}
library('fontawesome')
```

### `r fa("readme")` PENDAHULUAN

Modul ini membahas mengenai konsep dan penerapan portofolio. Topik-topik yang dibahas antara lain *attainable set*, *efficient set*, *efficient portfolio*. Konsep portofolio optimal yang dibahas antara lain prinsip Markowitz, prinsip optimal sudut terbesar dan risiko portofolio terkecil.

Sesudah mempelajari dengan baik modul ini Anda diharapkan mampu menerapkan konsep portofolio optimal. Lebih khusus lagi, mahasiswa diharapkan mampu:

- `r emo::ji('check')` menjelaskan konsep portofolio; 
- `r emo::ji('check')` menjelaskan pengertian attainable set;
- `r emo::ji('check')` menjelaskan pengertian dan menentukan set efisien;
- `r emo::ji('check')` menentukan portofolio optimal sesuai dengan preferensi risiko;
- `r emo::ji('check')` menentukan portofolio optimal sudut terbesar;
- `r emo::ji('check')` menentukan portofolio optimal risiko terkecil.

<br />


## `r emo::ji('books')` KEGIATAN BELAJAR 1: *ATTAINABEL SET* DAN *EFFICIENT SET*

### A. *Attainable Set*

- Kemungkinan proporsi aset di dalam sebuah portofolio sangat banyak
- Dua faktor yang perlu diperhatikan: return ekspektasian dan risiko portofolio.
- Menggambarkan attainable set: return ekspektasian di sumbu y dan risiko portofolio di sumbu x.

### B. Menentukan Set Efisien

- Berisi portofolio-portofolio baik/efisien
- Salah satu daru portofolio efisien adalah portofolio optimal/terbaik.

### C. Portofolio-Portofolio Efisien

- Portofolio yang memberikan return ekspektasian terbesar dengan risiko tertentu, atau
- Portofolio yang memberikan risiko yang terkecil dengan return tertentu.

<br />

## `r emo::ji('books')` KEGIATAN BELAJAR 2: MEMILIH PORTOFOLIO OPTIMAL

### A. Portofolio Optimal sesuai dengan Prinsip Markowitz


### B. Portofolio Optimal Sudut Terbesar

### C. Portofolio Risiko Terkecil

<br />
<br />

<!-- AddToAny BEGIN -->
<div class="a2a_kit a2a_kit_size_16 a2a_default_style"; data-a2a-url="https://bangtedy.github.io/etan" data-a2a-title="Konsep Portofolio">
<a class="a2a_button_whatsapp"></a>
<a class="a2a_button_telegram"></a>
<a class="a2a_button_facebook"></a>
<a class="a2a_button_twitter"></a>
</div>
<script async src="https://static.addtoany.com/menu/page.js"></script>
<!-- AddToAny END -->
