---
title: Saham
description: |
  Modul 4 EKSI4203
author: 
  - name: Tedy Herlambang
    url: https://bangtedy.github.io
    orcid_id: 0000-0002-7296-4357
date: '2022-04-22'
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## PENDAHULUAN

Modul ini membahas seluk beluk saham. Setelah mempelajari modul ini, mahasiswa diharapkan mampu menghitung nilai saham baik saham biasa ataupun saham preferen. Lebih khusus, mahasiswa diharapkan mampu:

- [x] menjelaskan konsep saham
- [x] menjelaskan pengertian nilai buku
- [x] menjelaskan pengertian nilai intrinsik
- [x] menghitung metode nilai sekarang aliran kas masa datang
- [x] menghitung model diskonto dividen
- [x] menghitung nilai intrinsik pendekatan relatif
- [x] menjelaskan pengertian nilai pasar saham.


---

## KEGIATAN BELAJAR 1: PEMAHAMAN SAHAM
### A. MACAM-MACAM SAHAM

- Kepemilikan perusahaan ditunjukkan dalam bentuk saham (stock). 
- Perusahaan dapat mengeluarkan saham biasa (common stock) dan saham preferen (preferred stock). 
- Perusahaan dapat mengeluarkan satu macam saham saja atau kedua-duanya. 
  + Jika hanya satu macam saham saja, biasanya yang dikeluarkan adalah saham biasa
  
#### 1. Saham Preferen

- Saham preferen mempunyai sifat gabungan (hybrid) antara obligasi (bond) dan saham biasa.
  + Seperti bond yang membayarkan bunga atas pinjaman, saham preferen juga memberikan hasil yang tetap berupa dividen preferen. 
  + Seperti saham biasa, dalam hal likuidasi, klaim pemegang saham preferen di bawah klaim pemegang obligasi (bond). 
  + Dibandingkan dengan saham biasa, saham preferen mempunyai beberapa hak, yaitu hak atas dividen tetap dan hak pembayaran terlebih dahulu jika terjadi likuidasi. 
  + Tetapi, saham preferen umumnya tidak mempunyai hak veto seperti yang dimiliki oleh saham biasa.

**Karakteristik Saham Preferen**

- Preferen terhadap dividen
- Hak dividen kumulatif
- Preferen waktu likuidasi

#### 2. Saham Biasa

- Jika perusahaan hanya mengeluarkan satu kelas saham saja, saham ini biasanya dalam bentuk saham biasa (common stock).

**Hak Pemegang Saham Biasa**

- Hak Kontrol
- Hak Preemtif
- Hak Menerima Pembagian Keuntungan


<br />

## KEGIATAN BELAJAR 2: NILAI-NILAI SAHAM
### A. NILAI NOMINAL

- Nilai nominal (par value) dari suatu saham merupakan nilai kewajiban yang ditetapkan untuk tiap-tiap lembar saham. 
- Untuk saham yang tidak mempunyai nilai nominal, dewan direksi umumnya menetapkan nilai sendiri (stated value) per lembarnya. 
- Jika tidak ada nilai yang ditetapkan, maka yang dianggap sebagai modal secara hukum adalah semua penerimaan bersih (proceed) yang diterima oleh emiten pada waktu mengeluarkan saham bersangkutan.

### B. NILAI BUKU

- Nilai buku (book value) per lembar saham menunjukkan aset bersih (net assets) yang dimiliki oleh pemegang saham dengan memiliki satu lembar saham. 
- Karena aset bersih adalah sama dengan total ekuitas pemegang saham, maka nilai buku per lembar saham adalah total ekuitas dibagi dengan jumlah saham yang beredar:

$$ Nilai\, buku\, per\, lembar = \frac {Total\,ekuitas}{Jumlah\,saham\,beredar}$$

#### 1. Nilai Buku Saham Preferen

#### 2. Nilai Buku Saham Biasa

### C. NILAI INSTRINSIK

- Nilai intrinsik adalah nilai sebenarnya yang diperkirakan. 
- Nilai intrinsik disebut juga dengan nilai fundamental (fundamental value). 
- Nilai intrinsik dapat dihitung dengan beberapa metode.


#### 1. Metode Nilai Sekarang Aliran Kas Masa Datang


$$ P_o^*= \sum_{t=1}^n \frac {Arus\,Kas_t}{(1+k)^t}  $$

#### 2. Model Diskonto Dividen


$$ P_o^*= \sum_{t=1}^n \frac {D_t}{(1+k)^t}  $$


a. Pembayaran Dividen Konstan

$$ P_o^* = \frac {D}{k}$$
b. Pembayaran Dividen Bertumbuh Konstan

$$ P_o^* = \frac {D_o(1+g)}{(1+k)} + \frac {D_o(1+g)^2}{(1+k)^2} + \frac {D_o(1+g)^3}{(1+k)^3} + ... + \frac {D_o(1+g)^n}{(1+k)^n}$$

Atau dapat disederhanakan menjadi:

$$P_o^* = \frac {D_o(1+g)}{(k-g)}$$
c. Pembayaran Dividen Tidak Beraturan

$$P_o^* = \frac {D_1}{(1+k)} + \frac {D_2}{(1+k)^2} + \frac {D_3}{(1+k)^3}+...+ \frac {D_n}{(1+k)^n}+\frac {NT_n}{(1+k)^n}$$

#### 3. Metode Relatif

\begin{align*}
P_o^* &= \frac {P_o}{E_1} * E_1\\
P_o^* &= PER * E_1
\end{align*}

