---
title: Return dan Risiko
author: Tedy Herlambang
date: '2022-04-12'
slug: return-dan-risiko
categories:
  - Materi
tags:
  - return
  - risiko
  - risk
  - tingkat pengembalian
---

```{r load_packages, echo=FALSE}
library ('fontawesome')
```

### `r fa("readme")` Pendahuluan

Modul ini membahas secara rinci dua faktor utama dalam mengambil keputusan investasi yaitu *return* dan risiko. Berbagai jenis return dan risk serta cara penghitungannya juga dibahas di modul ini.

Setelah mempelajari dengan baik modul ini Anda diharapkan mampu menghitung return dan risiko untuk aset tunggal dan portofolio dan konsep diversifikasi. Secara khusus Anda diharapkan mampu:

- [x] menjelaskan pengertiareturn suatu investasi,
- [x] menjelaskan pengertian return aset tunggal,
- [x] menjelaskan return realisasian,
- [x] menjelaskan return ekspektasian,
- [x] menjelaskan risiko aset tunggal,
- [x] menjelaskan koefisien variasi,
- [x] menjelaskan pengertian return portofolio,
- [x] menjelaskan return portofolio ekspektasian,
- [x] menjelaskan pengertian risiko portofolio,
- [x] menjelaskan risiko portofolio dua aset,
- [x] menjelaskan risiko portofolio banyak aset, dan
- [x] menjelaskan pengertian diversifikasi risiko portofolio.



## `r emo::ji('books')` KEGIATAN BELAJAR 1

### Return dan Risiko Aset Tunggal

A. RETURN ASET TUNGGAL

- Return: hasil yang diperoleh dari investasi
  + return realisasian (*realised return)
  + return ekspektasian
- Return realisasian: untuk mengukur kinerja investasi
  + return yang telah terjadi
  + dihitung dengan data historis
  + dasar untuk menghitung return ekspektasian dan risiko dimasa yad.
-Return ekspektasian:
  + belum terjadi tetapi diharapkan diperoleh di masa yad

#### 1. Return Realisasian

a. Return Total= capital gain (loss) + Yield

  + capital gain: kenaikan atau penurunan nilai investasi $(P_t - P_{(t-1)})/P_{(t-1)}$
  + Yield: income dari investasi

$$R_t = \frac {P_t - P_{(t-1)}} {P_{(t-1)}} + \frac {I_t}{P_{(t-1)}} $$ 
Catatan:

  + $R_t$ = Return periode t dari aset
  + $P_t$ = Harga periode t pada saat aset dijual
  + $P_{t-1}$ = Harga periode t-1 pada saat aset dibeli
  + $I_t$ = Income yang diperoleh dari pemanfaatan aset
  + $\frac {P_t - P_{(t-1)}} {P_{(t-1)}}$ = capital gain atau loss
  + $\frac {I_t}{P_{(t-1)}}$ = Yield

b. Relatif Return

Relatif return: hasil investasi $(P_t)$ relatif tehrdap nilai investasinya $(P_{t-1})$

$$Relatif \,Return_t =  \frac {P_t}{P_{t-1}} $$
Jika dividen diperhitungkan menjadi:

$$Relatif \,Return_t =  \frac {P_t}{P_{t-1}} + \frac {D_t}{P_{t-1}} $$

#### 2. Return Ekspektasian

- dihitung dari rataan data historis (asumsi re sama dengan rataan data historis)
  + rata-rata aritmetika
  + rata-rata geometrik

a. Rata-rata aritmetika E(R)

\begin{align*}
E(R_i) & = \frac {R_1 + R_2 + R_3 + ...+ R_n} {n}\\
E(R_i) & = \frac {\sum_{x = 1}^{n} R_i}{n}
\end{align*}

Keterangan:

  + E(Ri) = return ekspektasian saham i
  + Ri = return historis saham i
  + n = jumlah return historis

b. Rata-rata Geometrik


B. RISIKO ASET TUNGGAL

- Risiko diartikan sebagai penyimpangan atau deviasi dari hasil yang diekspektasikan.
- Menggunakan rumus deviasi standar (*standard deviation*)
- Rumus deviasi standar:

$$   
SD = \sigma = \sqrt \frac {{{\sum_{x = 1}^{n} [R_t} - {E(R)}}]^2} {n-1}
$$

Keterangan:

- SD = standard deviation
- Rt = nilai return ekspektasi periode ke-t
- E(R) = nilai ekspektasian (rata-rata return historis)
- n = jumlah observasi data historis untuk n>30. Jika n<30 digunakan n-1.


C. KOEFISIEN VARIASI

- Di dalam investasi dua faktor ini harus diperhatikan secara terintegrasi: return ekspektasian dan risiko aset, yaitu dengan menggunakan koefisien variasi (*coefficient of variation*):

$$CV_i = \frac {Risiko}{Return\,Ekspektasian}$$
Keterangan:

- Risiko: gunakan nilai SD
- Return ekspektasian: rata-rata aritmetika return historis


## `r emo::ji('books')` KEGIATAN BELAJAR 2

A. TUJUAN MEMBUAT PORTOFOLIO

- We need to be more tactical and not put all our eggs in one political basket
- Spread the risks and do not risk everything on the success of one venture.


B. RETURN PORTOFOLIO

**1. Portofolio berisi 2 Aset**

**Return Realisasian**

$$ Rp = w_1 . R_1 + w_2 . R_2 $$

Keterangan:

- Rp = return realisasian portofolio
- w1 = proporsi aset ke 1 di portofolio
- w2 = proporsi aset ke 2 di portofolio
- R1 = return realisasian sekuritas ke 1
- R2 = return realisasian sekuritas ke 2.

**Return Ekspektasian**

$$ E (Rp) = w_1.E(R_1) + w_2 . E(R_2)$$ 

Keterangan:

- E(Rp) = return ekspektasian portofolio
- w1 = proporsi aset ke 1 di portofolio
- w2 = proporsi aset ke 2 di portofolio
- E(R1) = return ekspektasian sekuritas ke 1
- E(R2) = return ekspektasian sekuritas ke 2.

**2. Portofolio berisi banyak Aset**

**RETURN REALISASIAN**

$$ Rp = w_1 . R_1 + w_2 . R_2 + w_3 . R_3 +...+ w_n .R_n $$

atau dapat dituliskan sebagai:

$$ Rp = {\sum_{x = 1}^{n} {(w_i.R_i)}}$$

Keterangan:

- Rp = return realisasian portofolio
- wi = proporsi aset ke i di portofolio
- Ri = return realisasian aset ke-i
- n = jumlah dari aset tunggal di dalam portofolio


**RETURN EKSPEKTASIAN**

\begin{align*}
E(Rp) & = w_1 . E(R_1) + w_2 . E(R_2) + w_3 . E(R_3) +...+ w_n .E(R_n)\\
E(Rp) & = {\sum_{x = 1}^{n} {(w_i.E(R_i)}}
\end{align*}


Keterangan:

- E(Rp) = return ekspektasian portofolio
- wi = proporsi aset ke i di portofolio
- E(Ri) = return ekspektasian aset ke-i
- n = jumlah dari aset tunggal di dalam portofolio


C. RISIKO PORTOFOLIO

- Risiko portofolio tidak sama dengan rata-rata tertimbang dari risiko masing-masing aset, tetapi bisa lebih kecil.
- Dua elemen risiko portofolio:
  + komponen varian return sekuritas
  + komponen kovarian return sekuritas
- Risiko portofolio dua aset:

$$\sigma_p^2 = w_1^2 \sigma_1^2+ w_2^2 \sigma_2^2+ w_1w_2 \sigma_{12}+w_2w_1 \sigma_{21}$$
karena $\sigma_{12}$ simetris dengan $\sigma_{21}$ yang nilainya sama, maka rumus menjadi:

$$ \sigma_p^2 = w_1^2 \sigma_1^2+ w_2^2 \sigma_2^2+ 2 w_1w_2 \sigma _{12}$$
Rumus ini dapat dikembangkan untuk portofolio dengan n-aset:

$$ \sigma_p^2 = [w_1^2 \sigma_1^2+ w_2^2 \sigma_2^2 + ...+ w_n^2 \sigma_n^2 ]+ [2 w_1w_2 \sigma _{12} + 2 w_1w_3 \sigma _{13}...+ 2 w_{n-1}w_n \sigma _{{n-1},n}]$$
Dua komponen Risiko Portofolio

**Varian**: semua varian dari aset-aset di dalam portofolio

$$ VAR = \sigma^2 = SD^2 = \frac {\sum_{n=1}^{n} [R_t -E(R)]^2} {n-1} $$
**Kovarian**: arah pergerakan dua buah variabel

$$ Cov (R_A,R_B) = \sigma_{A,B} = \frac {{\sum_{n=1}^{n} [R_{A,t} - E(R_A)] [R_{B,t} -E(R_B)]}} {n-1} $$

D. DIVERSIFIKASI RISIKO PORTOFOLIO

- Risiko portofolio dapat turun karena *comovement* antara dua aset.
- Risiko akan semakin turun jika nilai kovarian negatif.
- Risiko portofolio akan semakin terdiversifikasi jika jumlah *comovement* semakin banyak.
- Dua jenis risiko:
  + risiko perusahaan --> dapat didiversifikasi/non sistematik
  + risiko spesifik/unik/sistematik -->non diversifiable/market risk


<!-- AddToAny BEGIN -->
<div class="a2a_kit a2a_kit_size_16 a2a_default_style"; data-a2a-url="https://bangtedy.github.io/porto" data-a2a-title="Return dan Risiko">
<a class="a2a_button_facebook"></a>
<a class="a2a_button_twitter"></a>
<a class="a2a_button_whatsapp"></a>
<a class="a2a_button_telegram"></a>
</div>
<script async src="https://static.addtoany.com/menu/page.js"></script>
<!-- AddToAny END -->