---
title: Pengantar ke TPAI
author: Tedy Herlambang
date: '2022-03-31'
slug: pengantar-ke-tpai
categories:
  - Materi
tags:
  - Pengantar
  - Teori-Portofolio
  - Analisis-Investasi
---

### Capaian Pembelajaran

Setelah mempelajari modul ini, Anda `seharusnya` dapat:

1. Menjelaskan apa itu investasi
2. Menjelaskan alasan orang berinvestasi
3. Menjelaskan bagaimana investor mengukur return dari investasi (*the rate of return on an investment*)
4. Menjelaskan bagaimana investor mengukur risiko dari berbagai pilihan investasi
5. Menjelaskan pengertian dan instrumen pasar modal di Indonesia

---

### APAKAH INVESTASI ITU?

- Sepanjang hidup, Anda akan memperoleh dan mengeluarkan uang (*earning and spending money*). 
- Jarang, bahwa pendapatan/uang Anda saat ini akan sama dengan keinginan belanja Anda. 
  - Kadang-kadang uang kita lebih banyak dari keinginan "beli-beli".
  - Di waktu lain kita ingin membeli sesuatu yang lebih besar dari kemampuan keuangan kita saat ini 
  
  --> Apa yang biasanya dilakukan jika kondisi demikian: **MENABUNG ATAU BERHUTANG**

- Jika pendapatan saat ini lebih besar dari pengeluaran konsumsi yang diinginkan, orang cenderung untu menabung: 
  - Ditaruh dibawah bantal
  - Dipendam di halaman belakang sampai batas waktu diperlukan untuk konsumsi. 
  - Saat diambil dari bawah bantal atau digali dari halaman belakang jumlah uang tetap.
  
#### KEMUNGKINAN LAIN

- Menunda pemakaian uang saat ini agar mendapatkan uang lebih besar di masa depan yang bisa dipakai untuk konsumsi.

- Inilah salah satu alasan orang menabung

- Apa yang dilakukan oleh orang dengan tabungannya agar bertambah banyak jumlahnya disebut **investasi**.

- Sebaliknya orang yang pengeluarannya saat ini lebih besar dari pendapatannya, dia disebut pengutang dan harus membayar hutang itu di masa depan + bunganya.

- Jika Anda bisa menukarkan Rp 100 ribu sekarang dengan Rp 110 ribu setahun kemudian, maka tingkat bunganya adalah 10% (110/100-1).
- Jadi Anda menunda konsumsi sebesar Rp 100 ribu sekarang dengan harapan dapat mengkonsumsi barang dan jasa setahun kemudian senilai Rp 110 ribu. 
  - Asumsinya harga-harga barang tetap, dan ini jarang terjadi. Berapa inflasi di Indonesia tahun 2020? Tahun 2021?
  - Jika inflasi tinggi, orang dengan pendapatan tetap, daya belinya akan menurun!
 
---

### JADI INVESTASI ADALAH

- Merupakan tindakan seseorang untuk mengeluarkan uangnya atau kemampuan finansialnya dengan harapan seseorang tersebut dimasa yang akan datang akan memperoleh uang yang lebih besar jumlahnya dibandingkan dengan yang dia miliki pada saat ini ( Tandelilin, 2001 ).
- Orang itu disebut investor

- The “investor” can be an individual, a government, a pension fund, or a corporation.

- This definition also includes all types of investments, including investments by corporations in plant and equipment and investments by individuals in stocks, bonds, commodities, or real estate. 

### TUJUAN INVESTASI

-- > Untuk memperoleh sejumlah uang, sehingga dapat meningkatkan kemakmurannya.

Beberapa alasan mengapa seseorang berkeinginan untuk melakukan investasi:

- Memperoleh kehidupan yang lebih layak.
- Mengurangi tekanan inflasi
- Dorongan untuk menghemat pajak.

---

### PROSES INVESTASI

-  Perlu pemahaman tentang hubungan antara return yang akan diperoleh dibandingkan dengan risiko yang akan dihadapi pada suatu investasi.

### DASAR KEPUTUSAN INVESTASI
	
- Dasar keputusan seseorang untuk melakukan investasi tentunya adalah dari resiko yang akan dihadapinya, tingkat pengembalian atau keuntungan atau return yang akan diperolehnya dan hubungan antara risiko dan return.
 
#### RETURN

- Adalah keuntungan yang akan diperoleh pada waktu yang akan datang setelah seseorang melakukan investasi.

- Return yang diharapkan diperoleh investor tersebut dari investasi yang telah dilakukannya merupakan suatu kompensasi atas biaya kesempatan atau *opportunity cost* dan risiko penurunan daya beli dari seorang investor akibat adanya pengaruh investasi.

- *Opportunity cost* yang dimaksud disini adalah hilangnya kesempatan seorang investor untuk melakukan investasi lainnya atau konsumsi karena dia telah menentukan untuk memilih investasi tersebut. 

Return yang diharapkan dapat dibedakan menjadi 2, yaitu:

- Expected return (return dimasa yang akan datang)
- Realited return (return yang telah terjadi) 

Komponen dari pengembalian atau return dapat dikelompokkan menjadi dua, yaitu:  

- Untung/rugi modal (*capital gaint/loss*) merupakan keuntungan (kerugian) yang diperoleh investor dari kelebihan harga jual daripada harga beli atas kepemilikan surat berharga.
- Imbalan hasil (*yield*) merupakan pendapatan atau aliran kas yang diterima investor secara periodik. 

Dari kedua komponen pengembalian tersebut, dapat dihitung pengembalian total (total return) dengan rumus sebagai berikut :

$$Total\,Pengembalian = Capital\,Gain\,(Loss) + Yield$$


#### RISIKO

- Adalah kemungkinan return aktual yang berbeda dengan return yang diharapkan (*expected return*).
- Pada dasarnya semakin tinggi risiko yang akan ditanggung oleh seorang investor, maka return yang diharapkan untuk diperoleh untuk masa yang akan datang akan tinggi pula.

Berdasarkan tingkat preferensi investor terhadap risiko maka risiko investasi dapat dibedakan menjadi 3, yaitu:

- Investor yang menyukai risiko atau pencari risiko (*risk seeker*).
- Investor yang netral terhadap risiko (*risk neutral*).
- Investor yang tidak menyukai risiko (*risk averter*).

Beberapa jenis resiko yang mungkin terjadi dalam investasi adalah:

- Risiko suku bunga
- Risiko pasar
- Risiko inflasi
- Risiko bisnis
- Risiko finansial
- Risiko likuiditas
- Risiko nilai tukar mata uang

---

## PORTOFOLIO

- Almost everyone owns a portfolio (group) of assets. 
- This portfolio is likely to contain real assets, such as a car, a house, or a refrigerator, as well as financial assets, such as stocks and bonds.
- Komposisi dari portofolio itu mungkin berasal dari keputusan yang direncanakan secara cermat bisa juga dari keputusan yang tidak berkaitan. 

  - Misalkan Anda punya tanah, motor, emas, sapi, kebun mangga dan mungkin saham 
  - Mengapa komposisi aset yang Anda miliki demikian?
  - Di makul ini fokus pembahasan ke aset-aset keuangan (*financial assets*)

- Seorang investor menghadapi berbagai alternatif pilihan aset yang akan dipegang.
  - Apa dasar dari memilih berbagai alternatif tersebut?
  - Return and risk
  --> Kita akan membahas beberapa teori yang berhubungan dengan pilihan rasional dari alternatif aset, metode untuk implementasi dan pengawasan proses keputusan investasi. 

> Pertanyaan menarik: apakah seorang investor (atau kita sbg manusia) selalu mendasarkan keputusan (investasi atau keputusan lain) pada rasionalitas?

- Behavioural economics - behavioural finance

---

### Empat Pemain dalam Pasar Keuangan

1. Pengutang/peminjam/*borrowers*: mereka yang memerlukan dana untuk usaha mereka.
2. Penabung/investor/savers: mereka yang punya dana untuk investasi. 
3. Pedagang dan spekulan: mereka yang meminjam dan berinvestasi dengan tujuan mendapatkan profit dari pasar. 
4. Lembaga keuangan/perantara: lembaga keuangan yang mempertemukan peminjam dengan investor

### Lembaga Keuangan

- Bank komersial, 
- Perusahaan keuangan, 
- Perusahaan asuransi, 
- Bank investasi, dan 
- Perusahaan investasi.

--- >  membantu pergerakan uang dari pemilik uang (`investor`) ke pihak yang membutuhkan uang (`peminjam`).

---

### Pasar Keuangan: 

--> Atas dasar waktu jatuh tempo sekuritas yang diperdagangkan

- **Pasar Uang**: pasar yang menyediakan instrumen utang jangka pendek.

- **Pasar Modal**: pasar yang menyediakan instrumen utang dan ekuitas jangka panjang (misalnya saham biasa, saham preferen, obligasi perusahaan, obligasi pemerintah)

### Bank Komersial 

- Menghimpun dana tabungan dari para individual dan dunia usaha
- Meminjamkan uang yang terhimpun tersebut kepada pihak lain (individu dan perusahaan). 
- Bank mendapatkan uang dari selisih beban bunga peminjam yang lebih tinggi dari tingkat bunga penabung.

---

### Lembaga Keuangan Nonbank

- Perusahaan jasa keuangan
- Perusahaan asuransi
- Bank investasi
- Perusahaan investasi: mutual funds, hedge funds, and private equity firms

#### Perusahaan Jasa Keuangan

- Bergerak di bidang usaha peminjaman atau pendanaan, tetapi mereka bukanlah bank komersial
- Contoh: 

#### Perusahan Asuransi 

- Menjual polis asuransi kepada individu dan dunia usaha untuk melindungi investasi mereka.
- Menghimpun premi dan menahan premi tersebut dalam suatu cadangan (reserve) hingga terjadinya kerugian yang dipertanggungkan dan mereka akan membayar klaim kepada pemegang kontrak asuransi. 
- Cadangan ini dikelola ke dalam berbagai jenis investasi termasuk pinjaman kepada individu dan perusahaan.

#### Investment Bank

- Perantara keuangan khusus yang membantu perusahaan dan pemerintah dalam memperoleh uang
- Konsultasi kepada perusahaan ketika hendak masuk ke dalam transaksi besar seperti mergers.
- Contoh di Indonesia: 

---

### Mutual Funds and Exchange Traded Funds (ETFs)

- Mutual funds atau Reksa Dana dikelola secara profesional sesuai dengan tujuan investasi yang ditetapkan.
- Exchange-traded fund (ETF) mirip dengan mutual fund kecuali kepemilikan lembar ETF dapat diperjualbelikan di pasar saham.
- Sebagian besar ETF membentuk suatu indeks harga, seperti S&P 500.

### Reksa Dana dan ETF

- Efektif untuk mendiversifikasi dan mengurangi risiko
- Dengan membeli suatu Reksa Dana atau ETF yang diinvestasikan ke dalam S&P 500, 
  - berarti Anda dapat membeli portofolio yang berada di dalam saham-500 hanya dengan satu transaksi

---

### Sekuritas

- Suatu instrumen yang dapat dinegosiasi yang merepresentasikan suatu klaim keuangan. - Bentuknya bisa berupa saham atau instrumen utang.
- Pasar sekuritas mempertemukan para investor dunia usaha dan individu untuk memperdagangkan sekuritas yang diterbitkan oleh perusahaan publik.

#### Pasar Perdana dan Pasar Sekunder

- **Pasar perdana**: suatu pasar dimana sekuritas diperjualbelikan untuk pertama kalinya. 
  - Perusahaan yang menjual sekuritas mendapatkan sejumlah uang.

- **Pasar sekunder**: suatu pasar untuk perdagangan selanjutnya dari sekuritas yang telah diterbitkan sebelumnya. 
  - Perusahaan yang menerbitkan saham tidak menerima uang lagi.

---

### Jenis-jenis sekuritas

- Sekuritas utang: perusahaan meminjam uang dengan cara menjual sekuritas utang di pasar utang (debt market). 
- Utang diklasifikasikan berdasarkan periode jatuh tempo: 
  - kurang dari satu tahun (diterbitkan di pasar uang), 
  - satu hinggal 10 tahun (disebut Note, diterbitkan di pasar modal), 
  - lebih dari 10 tahun (disebut bond, diterbitkan di pasar modal).
- Sekuritas ekuitas: merepresentasikan kepemilihan dalam perusahaan.
- Terdapat dua tipe utama dari sekuritas ekuitas: saham biasa dan saham preferen.
  - Saham biasa merepresentasikan kepemilikan ekuitas di dalam suatu perusahaan, memiliki hak suara, dan memberikan hak mendapatkan profit berupa dividen kepada pemegangnya.
  - Saham preferen adalah suatu sekuritas ekuitas. 
  - Saham ini memberikan keistimewaan, secara relatif dibandingkan dengan pemegang saham biasa, dalam hal pembayaran dividen dan klaim atas aset.

---

### Pasar Saham

- Pasar saham adalah pasar publik dimana saham-saham perusahaan diperdagangkan.

- Pasar saham diklasifikasikan dalam bentuk bursa yang diorganisasi dan bentuk over-the-counter (OTC) markets
  - Bursa yang diorganisasi (organized security exchanges) secara fisik memiliki ruangan dan instrumen keuangan diperdagangkan di tempat-tempat mereka. 
  - Sebagai contoh: Bursa Efek Indonesia atau Indonesia Stock Exchange (IDX) di Jakarta 
  - NASDAQ (National Association of Securities Dealers Automated Quotations) merupakan suatu over-the-counter market dan menyebut dirinya sebagai “screen-based, floorless market”. 
- Di jaman *now*, bagaimana perbedaan antara organized security exchanges dengan over-the-counter-market?

---

### Bursa-Bursa Saham di Dunia

- Shanghai Stock Exchange (SSE)
- Tokyo Stock Exchange (TSE)
- New York Stock Exchange (NYSE)
- London Stock Exchange (LSE)
- BSE (Bombay Stock Exchange)
- dll

#### Data Keuangan di Ujung Jari

- Coba kunjungi situs https://finance.yahoo.com
- Coba masukkan di pojok kanan (tulisan Quote Lookup) nama perusahaan (*ticker*) yang menarik perhatian Anda!
- Perhatikan data yang ditampilkan!
- Apa maksud dari data-data tersebut?

<!-- AddToAny BEGIN -->
<div class="a2a_kit a2a_kit_size_16 a2a_default_style"; data-a2a-url="https://bangtedy.github.io/porto" data-a2a-title="Pengantar ke TPAI">
<a class="a2a_button_facebook"></a>
<a class="a2a_button_twitter"></a>
<a class="a2a_button_whatsapp"></a>
<a class="a2a_button_telegram"></a>
</div>
<script async src="https://static.addtoany.com/menu/page.js"></script>
<!-- AddToAny END -->
